# Set up and run this Streamlit App
import streamlit as st
# from helper_functions import llm # <--- Not needed anymore. The helper function is now directly called by `customer_query_handler` 🆕
from logics.customer_query_handler import process_user_message
from utils import llm # <--- This is the helper function that we have created 🆕
import pandas as pd


# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    layout="centered",
    page_title="My Streamlit App"
)
# endregion <--------- Streamlit App Configuration --------->

st.title("Streamlit App")

all_courses = st.Page("pages/2_View_All_Courses.py", title="View All Courses", icon="1️⃣")
about_us = st.Page("pages/3_About_Us.py", title="About Us", icon="2️⃣")

st.navigation({"Main": [all_courses, about_us]}).run()

form = st.form(key="form")
form.subheader("Prompt")

user_prompt = form.text_area("Enter your prompt here", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    #response = llm.get_completion(user_prompt) # <--- This calls the helper function that we have created 🆕
    #st.write(response) # <--- This displays the response generated by the LLM onto the frontend 🆕
    #print(f"User Input is {user_prompt}")
    #response = process_user_message(user_prompt) #<--- This calls the `process_user_message` function that we have created 🆕
    #st.write(response)
    #print(f"User Input is {user_prompt}")
    st.divider()

    response, course_details = process_user_message(user_prompt)
    st.write(response)

    st.divider()

    print(course_details)
    df = pd.DataFrame(course_details)
    df 